name: hcc
version: 0.1.0.0
github: "kvkenyon/hcc"
license: BSD-3-Clause
author: "Kevin Kenyon"
maintainer: "kwkenyon@protonmail.com"
copyright: "2023 Kevin Kenyon"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hcc#readme>
default-extensions:
  - OverloadedStrings
  - GADTs
  - ImportQualifiedPost
  - GeneralizedNewtypeDeriving
dependencies:
  - base >= 4.7 && < 5
  - parsec
  - pretty-simple
  - containers
  - array
  - bytestring
  - process >= 1.6.14
  - text
  - mtl
build-tools:
  - happy
  - alex
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src

executables:
  hcc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hcc

tests:
  hcc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hcc
